name: "\U0001F41E Bug Report"
description: Report an issue with wx-vue
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow the [Code of Conduct](https://github.com/alex8088/wx-vue-next/blob/master/CODE_OF_CONDUCT.md).
          required: true
        - label: Read the [Contributing Guidelines](https://github.com/alex8088/wx-vue-next/blob/master/CONTRIBUTING.md).
          required: true
        - label: Read the [docs](https://alex8088.github.io/wx-vue-next/docs/).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/alex8088/wx-vue-next/issues) that reports the same bug to avoid creating a duplicate.
          required: true
